FROM   t24registry.azurecr.io/temenos-app:ISB_APP_GOLD_FEB_11
COPY --chown=jboss:jboss Validata.jar /opt/jboss/wildfly/modules/com/temenos/t24/main/lib/
COPY --chown=jboss:root module.xml /opt/jboss/wildfly/modules/com/temenos/t24/main/
COPY --chown=jboss:jboss RSDefaultProperties.properties /srv/Temenos/properties/ 
